dataset: Novamag
dataset_path: data/novamag-magnetism.csv

pt_path: data/Periodic-table/periodic_table.xlsx
mm_path: data/Miedema-model/Miedema-model-reduced.xlsx

models:
  - linear
  - ridge
  - lasso
  - elasticnet
  - rf
  - xgb
  - svr
  - mlp

enable_data_visualization: true
enable_ablation_study: true

evaluation_mode: cross_validation

cv_folds: 10
cv_shuffle: true
cv_random_state: 0
cv_seeds: [0, 5, 10, 15, 20]
enable_hyperparameter_tuning: true

holdout_seeds: [0, 1, 2, 3, 4]
holdout_train_size: 0.8

tune_cv_folds: 3
tune_n_iter: 20

random_state: 0

feature_columns:
  - compoundradix
  - stoicentw
  - Zw
  - periodw
  - groupw
  - meltingTw
  - miedemaH
  - valencew
  - electronegw

compare_models: [rf, xgb]

interpret_model: rf
case_study_models: [rf, xgb, ridge]
